# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: helloworld.proto for package 'helloworld'

require 'grpc'
require 'helloworld'

module Helloworld
  module Hello

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'helloworld.Hello'

      rpc :SayHi, Person, Greeting
    end

    Stub = Service.rpc_stub_class
  end
end
